{
 "title": "Telegram dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "telegram_channel_title",
    "label": "telegram_channel_title",
    "query": "select channel_title from telegram_channel;"
   },
   { "name": "topic_modeling_words", "query": "10" },
   { "name": "time_frame", "label": "time_frame", "query": "DAY : 86400, HOUR : 3600" },
   { "name": "step", "query": "1" },
   { "name": "segment", "label": "segment", "query": "ukr, katsap, western" }
  ]
 },
 "panels": [
  {
   "title": "Metrics for segments",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of views for segement $segment",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "rawSql": "SELECT to_timestamp((EXTRACT(EPOCH FROM TIMESTAMP '${__from:date:YYYY-MM-DD}')) + (DIV(EXTRACT(EPOCH FROM DATE_TRUNC('${time_frame:text}', t1.post_date)) \r\n- (EXTRACT(EPOCH FROM TIMESTAMP '${__from:date:YYYY-MM-DD}')), (${time_frame:value}*${step})) * (${time_frame:value}*${step}))) AS aggregated_date, SUM(t1.view_count) as views_numb \r\nFROM telegram_post t1\r\nWHERE t1.segment = ${segment:sqlstring} AND t1.post_date BETWEEN '${__from:date:YYYY-MM-DD}' AND '${__to:date:YYYY-MM-DD}'\r\nGROUP BY aggregated_date \r\nORDER BY aggregated_date, SUM(t1.view_count) DESC\r\n"
      }
     ]
    },
    {
     "title": "Top phrases for segment ${segment} by period",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "rawSql": "select lower(topic_modeling_phrases) as phrase, count(lower(topic_modeling_phrases)) as occurences \r\nfrom telegram_post_phrase_topics t1 join telegram_post t2 on t1.telegram_post_id = t2.id \r\n\tjoin telegram_channel t3 on t2.channel_id = t3.channel_id \r\nwhere segment = ${segment:sqlstring} and $__timeFilter(post_date) \r\ngroup by lower(topic_modeling_phrases) \r\norder by occurences desc\r\nlimit ${topic_modeling_words};\r\n"
      }
     ]
    },
    {
     "title": "Number of reactions for segment $segment",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "rawSql": "SELECT to_timestamp((EXTRACT(EPOCH FROM TIMESTAMP '${__from:date:YYYY-MM-DD}')) + (DIV(EXTRACT(EPOCH FROM DATE_TRUNC('${time_frame:text}', t2.post_date)) \r\n- (EXTRACT(EPOCH FROM TIMESTAMP '${__from:date:YYYY-MM-DD}')), (${time_frame:value}*${step})) * (${time_frame:value}*${step}))) AS aggregated_date, SUM(t1.count) as reactions_numb \r\nFROM telegram_reaction t1 JOIN telegram_post t2 ON t1.post_id = t2.id JOIN telegram_channel t3 ON t2.channel_id = t3.channel_id\r\nWHERE t2.segment = ${segment:sqlstring} AND t2.post_date BETWEEN '${__from:date:YYYY-MM-DD}' AND '${__to:date:YYYY-MM-DD}' \r\nGROUP BY aggregated_date\r\nORDER BY aggregated_date"
      }
     ]
    },
    {
     "title": "Average sentiment for segment $segment",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "rawSql": "SELECT to_timestamp((EXTRACT(EPOCH FROM TIMESTAMP '${__from:date:YYYY-MM-DD}')) + (DIV(EXTRACT(EPOCH FROM DATE_TRUNC('${time_frame:text}', t1.post_date)) \r\n- (EXTRACT(EPOCH FROM TIMESTAMP '${__from:date:YYYY-MM-DD}')), (${time_frame:value}*${step})) * (${time_frame:value}*${step}))) AS aggregated_date, AVG(t1.sentiment_value) AS avg_sentiment \r\nFROM telegram_post t1 JOIN telegram_channel t2 ON t1.channel_id = t2.channel_id\r\nWHERE t1.segment = ${segment:sqlstring} AND t1.post_date BETWEEN '${__from:date:YYYY-MM-DD}' AND '${__to:date:YYYY-MM-DD}' AND t1.is_processed = TRUE\r\nGROUP BY aggregated_date\r\nORDER BY aggregated_date"
      }
     ]
    },
    {
     "title": "Number of comments for segment $segment",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "targets": [
      {
       "rawSql": "SELECT to_timestamp((EXTRACT(EPOCH FROM TIMESTAMP '${__from:date:YYYY-MM-DD}')) + (DIV(EXTRACT(EPOCH FROM DATE_TRUNC('${time_frame:text}', t2.post_date)) \r\n- (EXTRACT(EPOCH FROM TIMESTAMP '${__from:date:YYYY-MM-DD}')), (${time_frame:value}*${step})) * (${time_frame:value}*${step}))) AS aggregated_date, COUNT(t1.comment_id) as comment_numb \r\nFROM telegram_comment t1 JOIN telegram_post t2 ON t1.post_id = t2.id JOIN telegram_channel t3 ON t2.channel_id = t3.channel_id\r\nWHERE t2.segment = ${segment:sqlstring} AND t2.post_date BETWEEN '${__from:date:YYYY-MM-DD}' AND '${__to:date:YYYY-MM-DD}'\r\nGROUP BY aggregated_date\r\nORDER BY aggregated_date"
      }
     ]
    },
    {
     "title": "Top topics for segement ${segment} by period",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "rawSql": "select lower(topic_modeling) as word, count(lower(topic_modeling)) as occurences \r\nfrom telegram_post_topics t1 join telegram_post t2 on t1.telegram_post_id = t2.id \r\n\tjoin telegram_channel t3 on t2.channel_id = t3.channel_id \r\nwhere segment = ${segment:sqlstring} and $__timeFilter(post_date) \r\ngroup by lower(topic_modeling) \r\norder by occurences desc\r\nlimit ${topic_modeling_words};"
      }
     ]
    }
   ]
  },
  {
   "title": "Metrics for channels",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of views on channel ${telegram_channel_title}",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "rawSql": "SELECT to_timestamp((EXTRACT(EPOCH FROM TIMESTAMP '${__from:date:YYYY-MM-DD}')) + (DIV(EXTRACT(EPOCH FROM DATE_TRUNC('${time_frame:text}', t1.post_date)) \r\n- (EXTRACT(EPOCH FROM TIMESTAMP '${__from:date:YYYY-MM-DD}')), (${time_frame:value}*${step})) * (${time_frame:value}*${step}))) AS aggregated_date, SUM(t1.view_count) as views_numb \r\nFROM telegram_post t1 JOIN telegram_channel t2 ON t1.channel_id = t2.channel_id\r\nWHERE t2.channel_title = ${telegram_channel_title:sqlstring} AND t1.post_date BETWEEN '${__from:date:YYYY-MM-DD}' AND '${__to:date:YYYY-MM-DD}' \r\nGROUP BY aggregated_date\r\nORDER BY aggregated_date, SUM(t1.view_count) DESC"
      }
     ]
    },
    {
     "title": "Number of reactions on channel ${telegram_channel_title}",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "rawSql": "SELECT to_timestamp((EXTRACT(EPOCH FROM TIMESTAMP '${__from:date:YYYY-MM-DD}')) + (DIV(EXTRACT(EPOCH FROM DATE_TRUNC('${time_frame:text}', t2.post_date)) \r\n- (EXTRACT(EPOCH FROM TIMESTAMP '${__from:date:YYYY-MM-DD}')), (${time_frame:value}*${step})) * (${time_frame:value}*${step}))) AS aggregated_date, SUM(t1.count)\r\nFROM telegram_reaction t1 JOIN telegram_post t2 ON t1.post_id = t2.id JOIN telegram_channel t3 ON t2.channel_id = t3.channel_id \r\nWHERE t2.post_date BETWEEN '${__from:date:YYYY-MM-DD}' AND '${__to:date:YYYY-MM-DD}' AND t3.channel_title = ${telegram_channel_title:sqlstring}  \r\nGROUP BY aggregated_date\r\nORDER BY aggregated_date"
      }
     ]
    },
    {
     "title": "Number of comments on channel ${telegram_channel_title}",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "rawSql": "SELECT to_timestamp((EXTRACT(EPOCH FROM TIMESTAMP '${__from:date:YYYY-MM-DD}')) + (DIV(EXTRACT(EPOCH FROM DATE_TRUNC('${time_frame:text}', t2.post_date)) \r\n- (EXTRACT(EPOCH FROM TIMESTAMP '${__from:date:YYYY-MM-DD}')), (${time_frame:value}*${step})) * (${time_frame:value}*${step}))) AS aggregated_date, COUNT(t1.comment_id) AS comments_numb \r\nFROM telegram_comment t1 JOIN telegram_post t2 ON t1.post_id = t2.id JOIN telegram_channel t3 ON t2.channel_id = t3.channel_id \r\nWHERE t2.post_date BETWEEN '${__from:date:YYYY-MM-DD}' AND '${__to:date:YYYY-MM-DD}' AND t3.channel_title = ${telegram_channel_title:sqlstring} \r\nGROUP BY aggregated_date\r\nORDER BY aggregated_date"
      }
     ]
    },
    {
     "title": "Top topics on channel ${telegram_channel_title} by period",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "rawSql": "select lower(topic_modeling) as word, count(lower(topic_modeling)) as occurences \r\nfrom telegram_post_topics t1 join telegram_post t2 on t1.telegram_post_id = t2.id \r\n\tjoin telegram_channel t3 on t2.channel_id = t3.channel_id \r\nwhere channel_title = ${telegram_channel_title:sqlstring} and $__timeFilter(post_date) \r\ngroup by lower(topic_modeling) \r\norder by occurences desc\r\nlimit ${topic_modeling_words};"
      }
     ]
    },
    {
     "title": "Top phrases on channel ${telegram_channel_title} by period",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "targets": [
      {
       "rawSql": "select lower(topic_modeling_phrases) as phrase, count(lower(topic_modeling_phrases)) as occurences \r\nfrom telegram_post_phrase_topics t1 join telegram_post t2 on t1.telegram_post_id = t2.id \r\n\tjoin telegram_channel t3 on t2.channel_id = t3.channel_id \r\nwhere channel_title = ${telegram_channel_title:sqlstring} and $__timeFilter(post_date) \r\ngroup by lower(topic_modeling_phrases) \r\norder by occurences desc\r\nlimit ${topic_modeling_words};"
      }
     ]
    },
    {
     "title": "Sentiment values for posts of channel $telegram_channel_title",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "targets": [
      {
       "rawSql": "SELECT to_timestamp((EXTRACT(EPOCH FROM TIMESTAMP '${__from:date:YYYY-MM-DD}')) + (DIV(EXTRACT(EPOCH FROM DATE_TRUNC('${time_frame:text}', t1.post_date)) \r\n- (EXTRACT(EPOCH FROM TIMESTAMP '${__from:date:YYYY-MM-DD}')), (${time_frame:value}*${step})) * (${time_frame:value}*${step}))) AS aggregated_date, AVG(t1.sentiment_value)\r\nFROM telegram_post t1 JOIN telegram_channel t2 ON t1.channel_id = t2.channel_id\r\nWHERE t1.post_date BETWEEN '${__from:date:YYYY-MM-DD}' AND '${__to:date:YYYY-MM-DD}' AND t2.channel_title = ${telegram_channel_title:sqlstring} AND t1.is_processed = TRUE\r\nGROUP BY aggregated_date\r\nORDER BY aggregated_date"
      }
     ]
    }
   ]
  }
 ]
}