{
 "title": "Telegram dashboard",
 "time": { "from": "2024-03-31T21:00:00.000Z", "to": "2024-04-29T20:59:59.000Z" },
 "templating": {
  "list": [
   {
    "name": "telegram_channel_title",
    "label": "telegram_channel_title",
    "query": "select channel_title from telegram_channel;"
   },
   { "name": "topic_modeling_words", "query": "10" },
   { "name": "top_x_posts", "query": "10" }
  ]
 },
 "panels": [
  { "title": "Engagement metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Engagement by reactions for posts of channel ${telegram_channel_title}",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "select updated_at as time, sum(t1.count) / view_count as engagement \r\nfrom telegram_reaction t1 join telegram_post t2 on t1.post_id = t2.id \r\n\tjoin telegram_channel t3 on t2.channel_id = t3.channel_id \r\nwhere view_count > 0 and t3.channel_title = ${telegram_channel_title:sqlstring} and  $__timeFilter(updated_at) \r\ngroup by telegram_post_id, updated_at, view_count;"
    }
   ]
  },
  {
   "title": "Top ${top_x_posts} most engaged by reactions posts of channel ${telegram_channel_title}",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "rawSql": "select cast(updated_at as text) as updated, sum(t1.count) / view_count as engagement \r\nfrom telegram_reaction t1 join telegram_post t2 on t1.post_id = t2.id \r\n\tjoin telegram_channel t3 on t2.channel_id = t3.channel_id \r\nwhere view_count > 0 and t3.channel_title = ${telegram_channel_title:sqlstring} and $__timeFilter(updated_at) \r\ngroup by telegram_post_id, view_count, updated_at \r\norder by engagement desc\r\nlimit ${top_x_posts};"
    }
   ]
  },
  {
   "title": "Engagement by comments posts of channel ${telegram_channel_title}",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "select updated_at as time, cast(count(comment_id) as decimal) / view_count as engagement_by_comments \r\nfrom telegram_comment t1 join telegram_post t2 on t1.post_id = t2.id \r\n\tjoin telegram_channel t3 on t2.channel_id = t3.channel_id \r\nwhere view_count > 0 and t3.channel_title = ${telegram_channel_title:sqlstring} and $__timeFilter(updated_at) \r\ngroup by telegram_post_id, view_count, updated_at;"
    }
   ]
  },
  {
   "title": "Top ${top_x_posts} most commented posts on channel ${telegram_channel_title}",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "select cast(updated_at as text) as updated, count(comment_id) as number_of_comments \r\nfrom telegram_comment t1 join telegram_post t2 on t1.post_id = t2.id \r\n  join telegram_channel t3 on t2.channel_id = t3.channel_id \r\nwhere t3.channel_title = ${telegram_channel_title:sqlstring} and $__timeFilter(updated_at) \r\ngroup by telegram_post_id, updated_at \r\norder by number_of_comments desc\r\nlimit ${top_x_posts};"
    }
   ]
  },
  {
   "title": "Sentiment analysis & topic modeling",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 }
  },
  {
   "title": "Sentiment values of ${telegram_channel_title} posts",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "select updated_at as time, sentiment_value \r\nfrom telegram_post t1 join telegram_channel t2 on t1.channel_id = t2.channel_id \r\nwhere channel_title = ${telegram_channel_title:sqlstring} and $__timeFilter(updated_at) and is_processed = true;"
    }
   ]
  },
  {
   "title": "Topic modeling for channel ${telegram_channel_title}",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "rawSql": "select lower(topic_modeling) as word, count(lower(topic_modeling)) as occurences \r\nfrom telegram_post_topics t1 join telegram_post t2 on t1.telegram_post_id = t2.id \r\n\tjoin telegram_channel t3 on t2.channel_id = t3.channel_id \r\nwhere channel_title = ${telegram_channel_title:sqlstring} and $__timeFilter(updated_at) \r\ngroup by lower(topic_modeling) \r\norder by occurences desc\r\nlimit ${topic_modeling_words};"
    }
   ]
  }
 ]
}