{
 "title": "YouTube dashboard",
 "time": { "from": "2024-02-01T22:00:00.000Z", "to": "2024-05-02T20:59:59.000Z" },
 "templating": {
  "list": [
   {
    "name": "youtube_channel_title",
    "label": "youtube_channel_title",
    "query": "select title from youtube_channels"
   },
   { "name": "top_x_videos", "query": "50" },
   { "name": "time_frame", "label": "time_frame", "query": "DAY : 86400, HOUR : 3600" },
   { "name": "step", "label": "step", "query": "5" },
   { "name": "topic_modeling_words", "label": "topic_modeling_words", "query": "10" }
  ]
 },
 "panels": [
  { "title": "Metrics for channels", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of likes on the channel $youtube_channel_title",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT to_timestamp((EXTRACT(EPOCH FROM TIMESTAMP '${__from:date:YYYY-MM-DD}')) + (DIV(EXTRACT(EPOCH FROM DATE_TRUNC('${time_frame:text}', to_timestamp(t2.published_at/1000))) - (EXTRACT(EPOCH FROM TIMESTAMP '${__from:date:YYYY-MM-DD}')), (${time_frame:value}*${step})) * (${time_frame:value}*${step}))) AS aggregated_date, SUM(t2.likes) as likes_numb \r\nFROM youtube_videos t2 JOIN youtube_channels t3 ON t3.id = t2.channel_id\r\nWHERE t2.published_at/1000 BETWEEN (EXTRACT(EPOCH FROM TIMESTAMP '${__from:date:YYYY-MM-DD}')) AND (EXTRACT(EPOCH FROM TIMESTAMP '${__to:date:YYYY-MM-DD}')) AND t3.title = ${youtube_channel_title:sqlstring} AND t2.is_processed = TRUE\r\nGROUP BY aggregated_date\r\nORDER BY aggregated_date"
    }
   ]
  },
  {
   "title": "Top phrases on the channel ${youtube_channel_title} by period",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "rawSql": "select lower(topic_modeling_phrases) as word, count(lower(topic_modeling_phrases)) as occurences \r\nfrom youtube_caption_phrase_topics t1 join youtube_captions t2 on t1.youtube_caption_id = t2.id join youtube_videos t3 on t2.youtube_video_id = t3.youtube_video_id\r\n  join youtube_channels t4 on t3.channel_id = t4.id  \r\nwhere t4.title = ${youtube_channel_title:sqlstring} and t3.published_at/1000 BETWEEN (EXTRACT(EPOCH FROM TIMESTAMP '${__from:date:YYYY-MM-DD}')) AND (EXTRACT(EPOCH FROM TIMESTAMP '${__to:date:YYYY-MM-DD}')) \r\ngroup by lower(topic_modeling_phrases) \r\norder by occurences desc\r\nlimit ${topic_modeling_words};"
    }
   ]
  },
  {
   "title": "Number of comments on channel $youtube_channel_title",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT to_timestamp((EXTRACT(EPOCH FROM TIMESTAMP '${__from:date:YYYY-MM-DD}')) + (DIV(EXTRACT(EPOCH FROM DATE_TRUNC('${time_frame:text}', to_timestamp(t2.published_at/1000))) - (EXTRACT(EPOCH FROM TIMESTAMP '${__from:date:YYYY-MM-DD}')), (${time_frame:value}*${step})) * (${time_frame:value}*${step}))) AS aggregated_date, COUNT(t1.id) as comments_numb \r\nFROM youtube_comments t1 JOIN youtube_videos t2 ON t1.youtube_video_id = t2.youtube_video_id JOIN youtube_channels t3 ON t3.id = t2.channel_id\r\nWHERE t2.published_at/1000 BETWEEN (EXTRACT(EPOCH FROM TIMESTAMP '${__from:date:YYYY-MM-DD}')) AND (EXTRACT(EPOCH FROM TIMESTAMP '${__to:date:YYYY-MM-DD}')) AND t3.title = ${youtube_channel_title:sqlstring} AND t2.is_processed = TRUE\r\nGROUP BY aggregated_date\r\nORDER BY aggregated_date"
    }
   ]
  },
  {
   "title": "Average sentiment values for $youtube_channel_title ",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT to_timestamp((EXTRACT(EPOCH FROM TIMESTAMP '${__from:date:YYYY-MM-DD}')) + (DIV(EXTRACT(EPOCH FROM DATE_TRUNC('${time_frame:text}', to_timestamp(t2.published_at/1000))) - (EXTRACT(EPOCH FROM TIMESTAMP '${__from:date:YYYY-MM-DD}')), (${time_frame:value}*${step})) * (${time_frame:value}*${step}))) AS aggregated_date, AVG(t1.sentiment_value) as avg_sentiment \r\nFROM youtube_captions t1 JOIN youtube_videos t2 ON t1.youtube_video_id = t2.youtube_video_id JOIN youtube_channels t3 ON t3.id = t2.channel_id\r\nWHERE t2.published_at/1000 BETWEEN (EXTRACT(EPOCH FROM TIMESTAMP '${__from:date:YYYY-MM-DD}')) AND (EXTRACT(EPOCH FROM TIMESTAMP '${__to:date:YYYY-MM-DD}')) AND t3.title = ${youtube_channel_title:sqlstring} AND t2.is_processed = TRUE\r\nGROUP BY aggregated_date\r\nORDER BY aggregated_date"
    }
   ]
  },
  {
   "title": "Top topics on the channel ${youtube_channel_title} by period ",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "select lower(topic_modeling) as word, count(lower(topic_modeling)) as occurences \r\nfrom youtube_caption_topics t1 join youtube_captions t2 on t1.youtube_caption_id = t2.id join youtube_videos t3 on t2.youtube_video_id = t3.youtube_video_id\r\n  join youtube_channels t4 on t3.channel_id = t4.id \r\nwhere t4.title = ${youtube_channel_title:sqlstring} and t3.published_at/1000 BETWEEN (EXTRACT(EPOCH FROM TIMESTAMP '${__from:date:YYYY-MM-DD}')) AND (EXTRACT(EPOCH FROM TIMESTAMP '${__to:date:YYYY-MM-DD}')) \r\ngroup by lower(topic_modeling) \r\norder by occurences desc\r\nlimit ${topic_modeling_words};"
    }
   ]
  },
  {
   "title": "Most commented videos on channel ${youtube_channel_title} by period",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "rawSql": "select cast(TO_TIMESTAMP(t2.published_at / 1000) as text) as publish_date, count(*) as comments_number \r\nfrom youtube_comments t1 join youtube_videos t2 on t1.youtube_video_id = t2.youtube_video_id \r\n\tjoin youtube_channels t3 on t2.channel_id = t3.id \r\nwhere t3.title = ${youtube_channel_title:sqlstring} and t2.published_at/1000 BETWEEN (EXTRACT(EPOCH FROM TIMESTAMP '${__from:date:YYYY-MM-DD}')) AND (EXTRACT(EPOCH FROM TIMESTAMP '${__to:date:YYYY-MM-DD}')) \r\ngroup by t1.youtube_video_id, t2.published_at  \r\norder by comments_number desc \r\nlimit ${top_x_videos};"
    }
   ]
  },
  {
   "title": "Most liked videos on channel ${youtube_channel_title} by period",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "rawSql": "select cast(TO_TIMESTAMP(t1.published_at / 1000) as text) as publish_date, t1.likes as likes_number \r\nfrom youtube_videos t1 join youtube_channels t2 on t1.channel_id = t2.id \r\nwhere t2.title = ${youtube_channel_title:sqlstring} and t1.published_at/1000 BETWEEN (EXTRACT(EPOCH FROM TIMESTAMP '${__from:date:YYYY-MM-DD}')) AND (EXTRACT(EPOCH FROM TIMESTAMP '${__to:date:YYYY-MM-DD}')) \r\norder by likes_number desc\r\nlimit ${top_x_videos}"
    }
   ]
  }
 ]
}